// Owns disposable local dependencies, delegates load generation to real k6,
// then reconciles the asynchronous side effects before cleanup.
package main

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/json"
	"flag"
	"fmt"
	driver "github.com/go-sql-driver/mysql"
	"github.com/redis/go-redis/v9"
	"github.com/umi3730/adflow/internal/platform/migrate"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
	"time"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func run() (err error) {
	output := flag.String("output", "work/k6-lab/run-01", "new output directory")
	seconds := flag.Int("seconds", 20, "duration of baseline and moderate phase")
	rate := flag.Int("rate", 30, "moderate phase rounds/second")
	apiPath := flag.String("api", "work/end-to-end/api-linux", "Linux production API binary")
	k6Path := flag.String("k6", "work/k6-lab/k6-v2.2.0-linux-amd64/k6", "k6 executable")
	capacity := flag.Bool("capacity", false, "search verified Kafka business-loop capacity")
	backpressure := flag.Bool("backpressure", false, "verify baseline, intentional overload rejection, and recovery")
	confirmSeconds := flag.Int("confirm-seconds", 60, "duration per confirmation")
	fixedCapacityRate := flag.Int("capacity-rate", 0, "optional fixed business rate for three confirmations")
	flag.Parse()
	if *seconds < 5 || *seconds > 120 || *rate < 10 || *rate > 100 {
		return fmt.Errorf("seconds=5..120, rate=10..100 required")
	}
	dir, err := filepath.Abs(*output)
	if err != nil {
		return err
	}
	if err = os.Mkdir(dir, 0755); err != nil {
		return err
	}
	root, _ := os.Getwd()
	binary, _ := filepath.Abs(*apiPath)
	id := time.Now().UTC().Format("20060102_150405")
	schema := "adflow_k6lab_" + id
	topic := "adflow-k6lab-" + id
	dlq := topic + "-dlq"
	group := topic + "-group"
	result := map[string]any{"startedAt": time.Now().UTC(), "scenario": "k6 1/s smoke, 10/s baseline, configured moderate; 4 HTTP calls per business round", "secondsPerLoadPhase": *seconds, "moderateRate": *rate, "schema": schema, "goHarness": "isolation and final accounting only; actual load generated by k6", "timingBoundary": "k6 records HTTP acceptance; drain/proof is separate and is not per-request end-to-end latency"}
	var admin, db *sql.DB
	var api, redisProcess *exec.Cmd
	var rc *redis.Client
	created, topicsCreated := false, []string{}
	kafka := func(script string, args ...string) (string, error) {
		ctx, cancel := context.WithTimeout(context.Background(), 40*time.Second)
		defer cancel()
		cmd := exec.CommandContext(ctx, "/opt/adflow-runtime/kafka_2.13-4.3.1/bin/"+script, args...)
		cmd.Env = append(os.Environ(), "KAFKA_HEAP_OPTS=-Xmx128m -Xms64m")
		out, e := cmd.CombinedOutput()
		return string(out), e
	}
	defer func() {
		if err != nil {
			result["error"] = err.Error()
		}
		cleanup := map[string]any{}
		cleanup["apiStopped"] = stop(api) == nil
		cleanup["redisStopped"] = stop(redisProcess) == nil
		if rc != nil {
			_ = rc.Close()
		}
		if db != nil {
			_ = db.Close()
		}
		if created && admin != nil {
			_, e := admin.Exec("DROP DATABASE `" + schema + "`")
			cleanup["databaseDropped"] = e == nil
		}
		if admin != nil {
			_ = admin.Close()
		}
		for _, name := range topicsCreated {
			_, e := kafka("kafka-topics.sh", "--bootstrap-server", "127.0.0.1:9092", "--delete", "--if-exists", "--topic", name)
			cleanup[name+"Deleted"] = e == nil
		}
		if api != nil {
			_, e := kafka("kafka-consumer-groups.sh", "--bootstrap-server", "127.0.0.1:9092", "--delete", "--group", group)
			cleanup["groupDeleted"] = e == nil
		}
		result["cleanup"] = cleanup
		result["finishedAt"] = time.Now().UTC()
		raw, _ := json.MarshalIndent(result, "", "  ")
		_ = os.WriteFile(filepath.Join(dir, "proof.json"), raw, 0644)
	}()
	cfg := driver.NewConfig()
	cfg.User = "root"
	cfg.Net = "unix"
	cfg.Addr = "/var/run/mysqld/mysqld.sock"
	cfg.ParseTime = true
	cfg.Loc = time.UTC
	cfg.InterpolateParams = true
	cfg.Params = map[string]string{"time_zone": "'+00:00'"}
	admin, err = sql.Open("mysql", cfg.FormatDSN())
	if err != nil {
		return
	}
	if _, err = admin.Exec("CREATE DATABASE `" + schema + "` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"); err != nil {
		return
	}
	created = true
	cfg.DBName = schema
	db, err = sql.Open("mysql", cfg.FormatDSN())
	if err != nil {
		return
	}
	runner, e := migrate.NewRunner(db, "migrations")
	if e != nil {
		return e
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	versions, e := runner.Up(ctx)
	cancel()
	if e != nil {
		return e
	}
	result["migrations"] = versions
	redisAddr, e := freePort()
	if e != nil {
		return e
	}
	_, redisPort, _ := net.SplitHostPort(redisAddr)
	redisProcess = exec.Command("redis-server", "--bind", "127.0.0.1", "--port", redisPort, "--save", "", "--appendonly", "no")
	if err = launch(redisProcess, filepath.Join(dir, "redis.log")); err != nil {
		return
	}
	rc = redis.NewClient(&redis.Options{Addr: redisAddr, Protocol: 2, DisableIdentity: true})
	for i := 0; i < 50; i++ {
		if rc.Ping(context.Background()).Err() == nil {
			break
		}
		time.Sleep(100 * time.Millisecond)
	}
	if err = rc.Ping(context.Background()).Err(); err != nil {
		return
	}
	for _, name := range []string{topic, dlq} {
		if _, err = kafka("kafka-topics.sh", "--bootstrap-server", "127.0.0.1:9092", "--create", "--topic", name, "--partitions", "3", "--replication-factor", "1"); err != nil {
			return
		}
		topicsCreated = append(topicsCreated, name)
	}
	addr, e := freePort()
	if e != nil {
		return e
	}
	base := "http://" + addr
	settings := map[string]string{"ENV": "test", "HTTP_ADDR": addr, "MYSQL_DSN": cfg.FormatDSN(), "REDIS_ADDR": redisAddr, "CAMPAIGN_REPOSITORY": "mysql", "PROFILE_STORE": "mysql-redis", "DECISION_STORE": "mysql", "RESERVATION_ADAPTER": "redis", "EVENT_TRANSPORT": "kafka", "KAFKA_BROKERS": "127.0.0.1:9092", "KAFKA_TOPIC": topic, "KAFKA_DEAD_LETTER_TOPIC": dlq, "KAFKA_CONSUMER_GROUP": group, "AUTH_ENABLED": "true", "AUDIT_STORE": "mysql", "DEMO_DATA": "false", "AGENT_PROVIDER": "mock", "DECISION_RATE_LIMITER": "redis", "DECISION_TIMEOUT": "1s", "PROFILE_CACHE_TIMEOUT": "50ms"}
	api = exec.Command(binary)
	api.Dir = root
	for _, v := range os.Environ() {
		if !strings.HasPrefix(v, "ADFLOW_") {
			api.Env = append(api.Env, v)
		}
	}
	for k, v := range settings {
		api.Env = append(api.Env, "ADFLOW_"+k+"="+v)
	}
	if err = launch(api, filepath.Join(dir, "api.log")); err != nil {
		return
	}
	client := http.Client{Timeout: 2 * time.Second}
	ready := false
	for i := 0; i < 80; i++ {
		res, e := client.Get(base + "/readyz")
		if e == nil {
			_ = res.Body.Close()
			if res.StatusCode == 200 {
				ready = true
				break
			}
		}
		time.Sleep(100 * time.Millisecond)
	}
	if !ready {
		return fmt.Errorf("API not ready")
	}
	result["environment"] = map[string]any{"API": base, "apiLocation": "WSL Linux", "k6Executable": *k6Path, "mysql": "Unix socket", "redis": "dedicated process", "kafkaPartitions": 3, "auth": true, "audit": "MySQL", "candidateCache": "5s", "profileCache": "5m; prewarmed", "decisionTimeout": "1s", "profileCacheTimeout": "50ms", "historicalBackgroundRows": 0}
	hashes := map[string]string{}
	for _, name := range []string{"tests/load/k6-walkthrough.js", "tests/bench/k6-lab/main.go"} {
		b, e := os.ReadFile(name)
		if e != nil {
			return e
		}
		hashes[name] = fmt.Sprintf("%x", sha256.Sum256(b))
	}
	b, e := os.ReadFile(binary)
	if e != nil {
		return e
	}
	result["apiBinarySHA256"] = fmt.Sprintf("%x", sha256.Sum256(b))
	result["sourceSHA256"] = hashes
	version, e := exec.Command(*k6Path, "version").CombinedOutput()
	if e != nil {
		return e
	}
	result["k6Version"] = strings.TrimSpace(string(version))
	if *backpressure {
		result["backpressureExperiment"] = true
	}
	if *capacity || *backpressure {
		return runKafkaCapacity(db, rc, base, group, dir, *k6Path, *seconds, *confirmSeconds, *fixedCapacityRate, result, kafka)
	}
	winpath := func(path string) (string, error) {
		if !strings.HasSuffix(*k6Path, ".exe") {
			return path, nil
		}
		b, e := exec.Command("wslpath", "-w", path).Output()
		return strings.TrimSpace(string(b)), e
	}
	scriptPath, e := winpath(filepath.Join(root, "tests/load/k6-walkthrough.js"))
	if e != nil {
		return e
	}
	reportPath, e := winpath(filepath.Join(dir, "k6-summary.json"))
	if e != nil {
		return e
	}
	args := []string{"run", "--no-usage-report", "--no-color", "-e", "BASE_URL=" + base, "-e", fmt.Sprintf("SECONDS=%d", *seconds), "-e", fmt.Sprintf("RATE=%d", *rate), "-e", "REPORT_PATH=" + reportPath, scriptPath}
	result["k6Arguments"] = args
	fmt.Printf("Starting k6: smoke 1/s, baseline 10/s, moderate %d/s; each load phase %ds\n", *rate, *seconds)
	cmd := exec.Command(*k6Path, args...)
	f, e := os.Create(filepath.Join(dir, "k6-console.log"))
	if e != nil {
		return e
	}
	cmd.Stdout = io.MultiWriter(os.Stdout, f)
	cmd.Stderr = io.MultiWriter(os.Stderr, f)
	k6err := cmd.Run()
	_ = f.Close()
	if k6err != nil {
		result["k6Error"] = k6err.Error()
	}
	raw, e := os.ReadFile(filepath.Join(dir, "k6-summary.json"))
	if e != nil {
		return e
	}
	var summary struct {
		Metrics map[string]struct {
			Values map[string]float64 `json:"values"`
		} `json:"metrics"`
	}
	if e = json.Unmarshal(raw, &summary); e != nil {
		return e
	}
	expected := int64(summary.Metrics["accepted_rounds"].Values["count"])
	events := int64(summary.Metrics["accepted_events"].Values["count"])
	result["expectedAcceptedRounds"] = expected
	result["expectedAcceptedEvents"] = events
	if expected <= 0 {
		return fmt.Errorf("no accepted business samples; k6 setup/run error: %v", k6err)
	}
	drainStart := time.Now()
	var processed int64
	for time.Since(drainStart) < 60*time.Second {
		if err = db.QueryRow("SELECT COUNT(*) FROM processed_events").Scan(&processed); err != nil {
			return
		}
		if processed == events {
			break
		}
		time.Sleep(200 * time.Millisecond)
	}
	result["drainAfterK6Seconds"] = time.Since(drainStart).Seconds()
	counts := map[string]int64{}
	for name, query := range map[string]string{"decisions": "SELECT COUNT(*) FROM decisions", "settled": "SELECT COUNT(*) FROM event_settlements WHERE status='SETTLED'", "receipts": "SELECT COUNT(*) FROM event_receipts", "published": "SELECT COUNT(*) FROM event_outbox WHERE status='PUBLISHED'", "processed": "SELECT COUNT(*) FROM processed_events", "outboxNotPublished": "SELECT COUNT(*) FROM event_outbox WHERE status<>'PUBLISHED'", "impressions": "SELECT COALESCE(SUM(impressions),0) FROM campaign_metrics", "clicks": "SELECT COALESCE(SUM(clicks),0) FROM campaign_metrics", "conversions": "SELECT COALESCE(SUM(conversions),0) FROM campaign_metrics", "valueFen": "SELECT COALESCE(SUM(value_fen),0) FROM campaign_metrics"} {
		var n int64
		if err = db.QueryRow(query).Scan(&n); err != nil {
			return
		}
		counts[name] = n
	}
	result["durableCounts"] = counts
	var winner string
	if err = db.QueryRow("SELECT campaign_id FROM campaign_metrics WHERE impressions>0").Scan(&winner); err != nil {
		return
	}
	var day string
	if err = db.QueryRow("SELECT DATE_FORMAT(MIN(created_at),'%Y-%m-%d') FROM decisions").Scan(&day); err != nil {
		return
	}
	budgetRoot := "adflow:budget:" + day + ":" + winner
	spent, e := rc.Get(context.Background(), budgetRoot+":spent").Int64()
	if e != nil {
		return e
	}
	reserved, e := rc.Get(context.Background(), budgetRoot+":reserved").Int64()
	if e != nil {
		return e
	}
	result["redisBudget"] = map[string]int64{"spentFen": spent, "expectedSpentFen": expected * 5, "reservedFen": reserved}
	valid := expected > 0 && events == expected*3 && counts["decisions"] == expected && counts["settled"] == expected && counts["published"] == events && counts["processed"] == events && counts["receipts"] == events && counts["outboxNotPublished"] == 0 && counts["impressions"] == expected && counts["clicks"] == expected && counts["conversions"] == expected && counts["valueFen"] == expected*500 && spent == expected*5 && reserved == 0
	result["accountingPassed"] = valid
	offsets, e := kafka("kafka-consumer-groups.sh", "--bootstrap-server", "127.0.0.1:9092", "--describe", "--group", group)
	result["brokerConsumerGroupDescribe"] = offsets
	if e != nil {
		return e
	}
	fmt.Printf("ASYNC PROOF accepted=%d events=%d processed=%d settled=%d spentFen=%d reservedFen=%d valid=%v\n", expected, events, counts["processed"], counts["settled"], spent, reserved, valid)
	if k6err != nil {
		return fmt.Errorf("k6 threshold/run failed: %v", k6err)
	}
	if !valid {
		return fmt.Errorf("asynchronous accounting mismatch")
	}
	return nil
}
func freePort() (string, error) {
	l, e := net.Listen("tcp", "127.0.0.1:0")
	if e != nil {
		return "", e
	}
	defer l.Close()
	return l.Addr().String(), nil
}
func launch(cmd *exec.Cmd, path string) error {
	f, e := os.Create(path)
	if e != nil {
		return e
	}
	defer f.Close()
	cmd.Stdout = f
	cmd.Stderr = f
	return cmd.Start()
}
func stop(cmd *exec.Cmd) error {
	if cmd == nil || cmd.Process == nil {
		return nil
	}
	_ = cmd.Process.Signal(syscall.SIGTERM)
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	select {
	case e := <-done:
		return e
	case <-time.After(15 * time.Second):
		_ = cmd.Process.Kill()
		<-done
		return fmt.Errorf("forced process stop")
	}
}
